class CountriesList {
  static List<String> countries = [
    'Europe',
    'England',
    'Albania',
    'Algeria',
    'Austria',
    'Australia',
    'Belarus',
    'Belgium',
    'Bulgaria',
    'Spain',
    'Chile',
    'Croatia',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Egypt',
    'Ethiopia'
    'France',
    'Germany',
    'Greece',
    'Hungary',
    'India',
    'Israel',
    'Italy',
    'Japan'
    'Kazakhstan',
    'Kenya',
    'Kuwait',
    'Macedonia',
    'Malasyia',
    'Mexico',
    'Montenegro',
    'Morocco',
    'Netherlands',
    'Poland',
    'Portugal',
    'Romania',
    'Russia',
    'Rwanda',
    'Saudi Arabia',
    'South Africa',
    'Scotland',
    'Serbia',
    'Spain',
    'Switzerland',
    'Tanzania',
    'Tunisia',
    'Turkey',
    'Uganda',
    'Ukraine',
    'Uruguay',
    'USA',
    'Zambia',
  ];
}
